name: flutter_view_wrapper
description: A simple Flutter wrapper with a SafeArea, LayoutBuilder and SingleChildScrollView.
version: 1.0.0
repository: https://github.com/mj12358/flutter-view-wrapper

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
